/*
-- SCRIPT TO LIST ALL CITIES CONTAINED IN THE DATABASE HBTN_0D_USA.

EACH RECORD SHOULD DISPLAY: CITIES.ID - CITIES.NAME - STATES.NAME
RESULTS MUST BE SORTED IN ASCENDING ORDER BY CITIES.ID
YOU CAN USE ONLY ONE SELECT STATEMENT
THE DATABASE NAME WILL BE PASSED AS AN ARGUMENT OF THE MYSQL COMMAND
*/

SELECT cities.id, cities.name, states.name
FROM cities
JOIN states ON cities.state_id = states.id
ORDER BY cities.id ASC;
